[workspace]
authors = ["Mahesh Binzer-Panchal <mahesh.binzer-panchal@nbis.se>"]
channels = ["conda-forge", "bioconda"]
name = "workshop-scRNAseq"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]
preview = "quarto preview"

[dependencies]
quarto = ">=1.8.27,<2"
python = "==3.12.12"
numpy = "==2.3.5"
pandas = "==2.3.3"
petsc4py = "==3.24.4"
# jupyterlab = "==4.0.7"
# ipykernel = "==6.25.2"

[pypi-dependencies]
jupyterlab = "==4.0.7"
ipykernel = "==6.25.2"
bbknn = ">=1.6.0, <2"
gseapy = "==1.1.11"
matplotlib-venn = "==1.1.2"
anndata = "==0.12.10"
celltypist = "==1.7.1"
harmonypy = "==0.2.0"
matplotlib = "==3.10.8"
# numpy = "==2.3.5"
# pandas = "==2.3.3"
requests = "==2.32.5"
scanorama = "==1.7.4"
scanpy = "==1.12"
scikit-learn = "==1.6.1"
scrublet = "==0.2.3"
seaborn = "==0.13.2"
tqdm = "==4.67.3"
cellrank = ">=2.0.7, <3"
# petsc4py = "==3.24.4"
scipy = "==1.16.3"
scvelo = "==0.3.4"